// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Reqnroll_ProjectMars.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SkillScenarios")]
    public partial class SkillScenariosFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "SkillScenarios", "This feature file contains scenarios related to the profile page where a user can" +
                " manage their skills present in their profile.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "SkillScenarios.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
#line 6
    await testRunner.GivenAsync("I am logged in with valid credentials \"test@gmail.com\" and \"test1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.AndAsync("I am on the Skills tab on the user profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add new skills with different skill levels")]
        [NUnit.Framework.CategoryAttribute("ValidScenario")]
        [NUnit.Framework.TestCaseAttribute("Programming", "Beginner", null)]
        [NUnit.Framework.TestCaseAttribute("Automation", "Intermediate", null)]
        [NUnit.Framework.TestCaseAttribute("Administration", "Expert", null)]
        public async System.Threading.Tasks.Task AddNewSkillsWithDifferentSkillLevels(string skill, string level, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ValidScenario"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Skill", skill);
            argumentsOfScenario.Add("Level", level);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add new skills with different skill levels", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 11
 await testRunner.WhenAsync(string.Format("I add a new skill \"{0}\" with level \"{1}\"", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
 await testRunner.ThenAsync(string.Format("I should see \"{0}\" displayed with the corresponding level \"{1}\" in the skills tab" +
                            "", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User able to update skill name and level of any skills displayed in profile")]
        [NUnit.Framework.CategoryAttribute("ValidScenario")]
        public async System.Threading.Tasks.Task UserAbleToUpdateSkillNameAndLevelOfAnySkillsDisplayedInProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidScenario"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User able to update skill name and level of any skills displayed in profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Skill",
                            "Level"});
                table4.AddRow(new string[] {
                            "Programming",
                            "Beginner"});
                table4.AddRow(new string[] {
                            "Automation",
                            "Intermediate"});
                table4.AddRow(new string[] {
                            "Administration",
                            "Expert"});
#line 25
 await testRunner.GivenAsync("the following skills exist in the profile:", ((string)(null)), table4, "Given ");
#line hidden
#line 31
  await testRunner.WhenAsync("I click the update icon near the skill \"Automation\" and update level to \"UpdatedA" +
                        "utomation\" with level \"Expert\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
  await testRunner.ThenAsync("I should see the new skill \"UpdatedAutomation\" with a confirmation message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User able to delete any skill displayed in profile")]
        [NUnit.Framework.CategoryAttribute("ValidScenario")]
        public async System.Threading.Tasks.Task UserAbleToDeleteAnySkillDisplayedInProfile()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidScenario"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User able to delete any skill displayed in profile", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Skill",
                            "Level"});
                table5.AddRow(new string[] {
                            "Programming",
                            "Beginner"});
                table5.AddRow(new string[] {
                            "Automation",
                            "Intermediate"});
                table5.AddRow(new string[] {
                            "Administration",
                            "Expert"});
#line 37
 await testRunner.GivenAsync("the following skills exist in the profile:", ((string)(null)), table5, "Given ");
#line hidden
#line 43
  await testRunner.WhenAsync("I click the delete icon near the skill \"Automation\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
  await testRunner.ThenAsync("skill \"Automation\" should be deleted with confirmation message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Error message displayed while adding already existing skill")]
        [NUnit.Framework.CategoryAttribute("InvalidScenario")]
        public async System.Threading.Tasks.Task ErrorMessageDisplayedWhileAddingAlreadyExistingSkill()
        {
            string[] tagsOfScenario = new string[] {
                    "InvalidScenario"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Error message displayed while adding already existing skill", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Skill",
                            "Level"});
                table6.AddRow(new string[] {
                            "Programming",
                            "Beginner"});
                table6.AddRow(new string[] {
                            "Automation",
                            "Intermediate"});
                table6.AddRow(new string[] {
                            "Administration",
                            "Expert"});
#line 49
 await testRunner.GivenAsync("the following skills exist in the profile:", ((string)(null)), table6, "Given ");
#line hidden
#line 55
    await testRunner.WhenAsync("I try to add an already existing skill \"Programming\" with level \"Expert\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
    await testRunner.ThenAsync("error should be displayed on the skill tab of profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Error message displayed when I leave skill name or level field blank")]
        [NUnit.Framework.CategoryAttribute("InvalidScenario")]
        [NUnit.Framework.TestCaseAttribute("Testing", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "Expert", null)]
        [NUnit.Framework.TestCaseAttribute("", "", null)]
        public async System.Threading.Tasks.Task ErrorMessageDisplayedWhenILeaveSkillNameOrLevelFieldBlank(string skillName, string level, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InvalidScenario"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SkillName", skillName);
            argumentsOfScenario.Add("Level", level);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Error message displayed when I leave skill name or level field blank", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 60
  await testRunner.WhenAsync(string.Format("I leave skill details {0} or {1} fields blank while adding", skillName, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
  await testRunner.ThenAsync(string.Format("error should be displayed to enter skill details {0} and {1}", skillName, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User able to add skills with symbols and long characters")]
        [NUnit.Framework.CategoryAttribute("DestructiveScenario")]
        [NUnit.Framework.TestCaseAttribute("abcdgbahdjbsjd1111111jdkkkkkkkkkkkkkkkkkkkkkk", "Beginner", null)]
        [NUnit.Framework.TestCaseAttribute("#$%^&!*@#@#", "Intermediate", null)]
        [NUnit.Framework.TestCaseAttribute("漢字漢字漢字漢字漢字漢字", "Expert", null)]
        public async System.Threading.Tasks.Task UserAbleToAddSkillsWithSymbolsAndLongCharacters(string skill, string level, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DestructiveScenario"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Skill", skill);
            argumentsOfScenario.Add("Level", level);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("User able to add skills with symbols and long characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 71
 await testRunner.WhenAsync(string.Format("I add a new skill \"{0}\" with level \"{1}\"", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
 await testRunner.ThenAsync(string.Format("I should see \"{0}\" displayed with the corresponding level \"{1}\" in the skills tab" +
                            "", skill, level), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
